"""order model add shop_id

Revision ID: 46b714e29816
Revises: 7c1be81e46ae
Create Date: 2020-10-15 14:21:00.842526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46b714e29816'
down_revision = '7c1be81e46ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('shop_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orders', 'shops', ['shop_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'shop_id')
    # ### end Alembic commands ###
