"""new model desk

Revision ID: 4daebdf331f1
Revises: 46b714e29816
Create Date: 2020-10-17 10:44:45.274704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4daebdf331f1'
down_revision = '46b714e29816'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('desks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('desk_size', sa.Integer(), nullable=True),
    sa.Column('desk_num', sa.Integer(), nullable=True),
    sa.Column('disabled', sa.Boolean(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('room', sa.Integer(), nullable=True),
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('desks')
    # ### end Alembic commands ###
